
package parqueadero.presentacion;

import java.awt.Image;
import java.awt.Toolkit;
import parqueadero.negocio.GestorLogin;
import parqueadero.negocio.Login;
import javax.swing.JButton;
import mvcf.AModel;
import mvcf.AView;
import parqueadero.utils.Utilidades;

/**
 *
 * @author Guido,Maria,Yennyfer
 */
public class GUILOGIN extends javax.swing.JFrame implements AView {

    /**
     * Creates new form GUILOGIN
     */
    String accion;
    /**
     * Constructor por Defecto.
     */
    public GUILOGIN() {
        initComponents();
        setSize(490, 190);
        setLocation(50, 260);
        setLocationRelativeTo(null);
        jtxt_user.setText("44");
        jtxt_pass.setText("admin");
        this.setResizable(false);
    }
    
     public boolean validarFormulario() {
        if (this.getUser().equals("")) {
            Utilidades.mensajeAdvertencia("Debe agregar nombre de Usuario", "Atención");
            jtxt_user.requestFocus();
            return false;
        }
        if (this.getPass().equals("")) {
            Utilidades.mensajeAdvertencia("Debe agregar contraseña del Usuario.", "Atención");
            jtxt_pass.requestFocus();
            return false;
        }
        return true;
    }
    
     public String getUser() {
        return jtxt_user.getText().trim();
    }
    public String getPass() {
        return jtxt_pass.getText().trim();
    }
    public String getAccion() {
        return accion;
    }

    public void setAccion(String accion) {
        this.accion = accion;
    }
    
    public JButton getBtnIniciar(){
        return jbtn_save;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Norte = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlSur = new javax.swing.JPanel();
        jbtn_save = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_user = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxt_pass = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/car.png"))); // NOI18N
        jLabel4.setText("PARQUEADERO UNICAUCA");
        Norte.add(jLabel4);
        jLabel4.getAccessibleContext().setAccessibleParent(this);

        getContentPane().add(Norte, java.awt.BorderLayout.PAGE_START);

        jbtn_save.setBackground(new java.awt.Color(0, 102, 153));
        jbtn_save.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jbtn_save.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_save.setText("Iniciar Sesion");
        jbtn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_saveActionPerformed(evt);
            }
        });
        pnlSur.add(jbtn_save);

        getContentPane().add(pnlSur, java.awt.BorderLayout.SOUTH);

        pnlCentro.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID Usuario");
        pnlCentro.add(jLabel3);

        jtxt_user.setBackground(new java.awt.Color(204, 56, 56));
        jtxt_user.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxt_user.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_userKeyTyped(evt);
            }
        });
        pnlCentro.add(jtxt_user);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Contraseña");
        pnlCentro.add(jLabel5);

        jtxt_pass.setBackground(new java.awt.Color(204, 56, 56));
        jtxt_pass.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jtxt_pass.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlCentro.add(jtxt_pass);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/user.png"))); // NOI18N
        jPanel2.add(jLabel1);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/K1.png"))); // NOI18N
        jLabel7.setText("  ");
        jPanel2.add(jLabel7);

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_saveActionPerformed
        accion = "INGRESAR";
        GestorLogin gestor_log = new GestorLogin();
        Login log  = null;
        log = gestor_log.buscarLogin(Integer.parseInt(getUser()), getPass());
        
        if(log!=null){
            if(gestor_log.esAdministrador(getUser())){
                MenuAdministrador obj = new MenuAdministrador();
                MenuAdministrador.jbtn_nom_vig.setText(""+log.getUsuario().toUpperCase());//Nombre actual del vigilante
                obj.setVisible(true);
                this.dispose();
            }else{
                MenuVigilante obj = new MenuVigilante();
                MenuVigilante.identificacion_vigilante_in = gestor_log.consultarIdentificacionVigilante(""+log.getId());
                String porteria = gestor_log.consultarPorteriaVigilante(""+log.getId());
                MenuVigilante.porteria_vig = porteria;
                //Menu.jbl_nom_actual.setText(""+log.getUsuario().toUpperCase()+"   ");//Nombre actual del vigilante
                MenuVigilante.jbtn_nom_vig.setText(""+log.getUsuario().toUpperCase()+" ["+porteria+"] ");//Nombre actual del vigilante
                obj.setVisible(true);
                this.dispose();
            }
        }else{
            System.out.println("Problemas al iniciar sesion");
        }
    }//GEN-LAST:event_jbtn_saveActionPerformed

    private void jtxt_userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_userKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtxt_userKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Norte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_save;
    private javax.swing.JTextField jtxt_pass;
    private javax.swing.JTextField jtxt_user;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlSur;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel amodel) {
        
    }
    
       @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("recursos/logoI.png"));

        return retValue;
    }
}
