package parqueadero.presentacion;

import java.awt.Color;
import javax.swing.ButtonModel;
import parqueadero.utils.Utilidades;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import mvcf.AModel;
import mvcf.AView;
import parqueadero.negocio.GestorRol;
import parqueadero.negocio.GestorVehiculos;
import parqueadero.negocio.Rol;
import parqueadero.negocio.Vehiculo;

/**
 *
 * @author Guido,Maria,Yennyfer
 *
 */
public class GUIVehiculos extends javax.swing.JFrame implements AView {

    //private GestorClientes gestor;
    /**
     * acción que define si es: AGREGAR, EDITAR o ELIMINAR
     */
    private String accion;

    /**
     * Constructor
     */
    public GUIVehiculos() {
        initComponents();
        setSize(530, 290);
        setLocation(50, 260);
        setLocationRelativeTo(null);
        txtId.setText("11111");
    }

    public JRadioButton getRBtnIdentificacion() {
        return jrbtn_identificacion;
    }

    public JRadioButton getRBtnCodigo() {
        return jrbtn_codigo;
    }

    /**
     * Mensaje inicial del panel superior
     */
    private void fijarMensajeExplicacion() {
        StringBuilder sb = new StringBuilder(64);
        sb.append("<html>" + "Este ejercicio es cliente/servidor y utiliza un miniframework MVC.<br>"
                + "La aplicación cliente se conecta al servidor (ServidorCentral) mediante Sockets.<br>"
                + "Si el id del cliente no está en la bd de la Parqueadero, la solicita a al ServidorCentral.<br>"
                + "La aplicación, además, tiene persistencia mediante Jdbc.<br>"
                + "</html>");
        //lblExplicacion.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlNorte = new javax.swing.JPanel();
        lb_error = new javax.swing.JLabel();
        pnlCentro1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jrbtn_identificacion = new javax.swing.JRadioButton();
        jrbtn_codigo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jtxt_rol = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();

        setTitle("Clientes");

        pnlNorte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlNorte.add(lb_error);

        getContentPane().add(pnlNorte, java.awt.BorderLayout.SOUTH);

        pnlCentro1.setBackground(new java.awt.Color(0, 102, 153));
        pnlCentro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCentro1.setLayout(new java.awt.GridLayout(3, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu Vigilante ");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlCentro1.add(jLabel3);

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
        });
        pnlCentro1.add(txtId);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Busqueda por:");
        pnlCentro1.add(jLabel1);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jrbtn_identificacion.setBackground(new java.awt.Color(204, 204, 255));
        btnGroup.add(jrbtn_identificacion);
        jrbtn_identificacion.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jrbtn_identificacion.setText("Identificacion");
        jrbtn_identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn_identificacionActionPerformed(evt);
            }
        });
        jPanel1.add(jrbtn_identificacion);

        jrbtn_codigo.setBackground(new java.awt.Color(204, 204, 255));
        btnGroup.add(jrbtn_codigo);
        jrbtn_codigo.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jrbtn_codigo.setText("Codigo");
        jrbtn_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn_codigoActionPerformed(evt);
            }
        });
        jPanel1.add(jrbtn_codigo);

        pnlCentro1.add(jPanel1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Rol:");
        pnlCentro1.add(jLabel4);

        jtxt_rol.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        pnlCentro1.add(jtxt_rol);

        getContentPane().add(pnlCentro1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setBackground(new java.awt.Color(0, 102, 153));

        tblVehiculos.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblVehiculos);

        jPanel3.add(jScrollPane2);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtn_identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn_identificacionActionPerformed

        String id = txtId.getText().trim();
        if (jrbtn_identificacion.isSelected()) {
            lb_error.setText("");
            if (id.equals("")) {
                validarFormulario();
                return;
            }
            setId(id);
            GestorVehiculos gestor_veh = new GestorVehiculos();
            GestorRol gestor_rol = new GestorRol();
            try {
                Rol obj_rol = gestor_rol.obtenerRolPerDeServidorCentral(id);
                if(obj_rol == null){
                    jtxt_rol.setText("");
                }else{
                   jtxt_rol.setText(obj_rol.getRol_nom());
                }
            } catch (Exception e) {
                System.out.println("Error desde consultar nombre rol: "+e.getMessage());
                e.printStackTrace();
            }
            try {
                Vehiculo[] listado = gestor_veh.buscarVehiculosXPersona(id); //GARRAFAL_VACIO
                if (listado != null) {
                    pnlNorte.setBackground(Color.LIGHT_GRAY);
                    llenarTabla(listado);
                } else {
                    inicializarTabla();
                    pnlNorte.setBackground(Color.red);
                    lb_error.setForeground(Color.white);
                    lb_error.setText("No tiene vehiculos registrados"); 
                }
            } catch (Exception e) {
                System.out.println("ERROR al cargar la Tabla " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jrbtn_identificacionActionPerformed

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed
        btnGroup.clearSelection();
        DefaultTableModel modelo_tabla = (DefaultTableModel) tblVehiculos.getModel();
        //modelo_tabla.setRowCount(0);
        while (modelo_tabla.getRowCount() > 0) {
            modelo_tabla.removeRow(0);
        }
    }//GEN-LAST:event_txtIdKeyPressed

    private void jrbtn_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn_codigoActionPerformed
        
        String id = txtId.getText().trim();

        if (jrbtn_codigo.isSelected()) {
            lb_error.setText("");
            if (id.equals("")) {
                validarFormulario();
                return;
            }
            setId(id);
            GestorVehiculos gestor_veh = new GestorVehiculos();
            GestorRol gestor_rol = new GestorRol();
            try {
                Rol obj_rol = gestor_rol.obtenerRolPerDeServidorCentral(id);
                if(obj_rol == null){
                    jtxt_rol.setText("");
                }else{
                    jtxt_rol.setText(obj_rol.getRol_nom());
                }
            } catch (Exception e) {
                System.out.println("Error desde consultar nombre rol: "+e.getMessage());
                e.printStackTrace();
            }
            try {
                Vehiculo[] listado = gestor_veh.buscarVehiculosXPersonaCodigo(id); //GARRAFAL_VACIO
                if (listado != null) {
                    llenarTabla(listado);
                } else {
                    inicializarTabla();
                    pnlNorte.setBackground(Color.red);
                    lb_error.setForeground(Color.white);
                    lb_error.setText("No tiene vehiculos registrados");
                }
            } catch (Exception e) {
                System.out.println("ERROR al cargar la tabla " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jrbtn_codigoActionPerformed
    
    /**
     * Valida que los datos estén correctamente diligenciados en el formulario
     *
     * @return true si están bien diligenciados, false en caso contrario
     */
    public boolean validarFormulario() {
        if (this.getId().equals("")) {
            Utilidades.mensajeAdvertencia("Debe agregar la identificación del involucrado", "Atención");
            txtId.requestFocus();
            return false;
        }
        return true;
    }

    public void setId(String dato) {
        txtId.setText(dato);
    }

    public String getId() {
        return txtId.getText().trim();
    }

    public String getRol() {
        return jtxt_rol.getText();
    }

    public void limpiarCajas() {
        //if (todas) {
            txtId.setText("");
            jtxt_rol.setText("");
        //}
    }

    private void inicializarTabla() {
        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id/cod", "Placa", "Marca", "Tipo"
                }
        ));
    }

    private void llenarTabla(Vehiculo[] vehiculos) {
        this.inicializarTabla();
        DefaultTableModel model = (DefaultTableModel) tblVehiculos.getModel();

        Object rowData[] = new Object[7];

        for (Vehiculo veh : vehiculos) {
            rowData[0] = veh.getIdentificacion();
            rowData[1] = veh.getPlaca();
            rowData[2] = veh.getMarca();
            rowData[3] = veh.getTipo();
            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton jrbtn_codigo;
    private javax.swing.JRadioButton jrbtn_identificacion;
    private javax.swing.JTextField jtxt_rol;
    private javax.swing.JLabel lb_error;
    private javax.swing.JPanel pnlCentro1;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JTable tblVehiculos;
    public static javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel amodel) {

    }

    public String getAccion() {
        return accion;
    }

    public void setAccion(String accion) {
        this.accion = accion;
    }

}
